# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu_13.04"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"
  ## PBS and salt relies on this
  ## DO NOT CHANGE THE NAME!
  config.vm.hostname = "torqueserver"

  ## load the salt folder
  config.vm.synced_folder "../salt/roots/", "/srv/"
  # provision
  config.vm.provision :salt do |salt|
    salt.minion_config = "../salt/minion"
    salt.run_highstate = true
  end
end
